names = {
            '01. Duc': '01. Duc',
            '02. Ospedale Maggiore': '02. Ospedale Maggiore', 
            '03. Traversetolo': '03. Traversetolo', 
            '04. Campus Chimica': '04. Campus Chimica', 
            '05. Stazione FF.SS.': '05. Stazione FF.SS.', 
            '06. Ponte di Mezzo': '06. Ponte di Mezzo', 
            '07. Santa Croce': '07. Santa Croce', 
            '08. Bixio': '08. Bixio', 
            '09. Farini': '09. Farini', 
            '10. Barilla Center': '10. Barilla Center', 
            '11. Dus': '11. Dus', 
            '12. Barezzi': '12. Barezzi', 
            '13. Borgo XX Marzo': '13. Borgo XX Marzo', 
            '14. Garibaldi': '14. Garibaldi', 
            '15. Repubblica': '15. Repubblica', 
            '16. Toschi': '16. Toschi', 
            '17. Rondani': '17. Rondani', 
            '18. Crocetta': '18. Crocetta', 
            '19. Boito': '19. Boito', 
            '20. Efsa': '20. Efsa', 
            '21. Kennedy': '21. Kennedy', 
            '22. Cittadella': '22. Cittadella', 
            '23. Vittoria': '23. Vittoria', 
            '24. Campus': '24. Campus', 
            '25. Ospedale': '25. Ospedale', 
            '25. Ospedale - viale Osacca': '25. Ospedale', 
            '26. Palasport': '26. Palasport', 
            'Barezzi': '12. Barezzi', 
            'Barilla Center': '10. Barilla Center', 
            'Bixio': '08. Bixio', 
            'Boito': '19. Boito', 
            'Borgo XX Marzo': '13. Borgo XX Marzo', 
            'Campus': '24. Campus', 
            'Campus Chimica': '04. Campus Chimica', 
            'Cittadella': '22. Cittadella', 
            'Crocetta': '18. Crocetta', 
            'Duc': '01. Duc', 
            'Dus': '11. Dus', 
            'Efsa': '20. Efsa', 
            'Farini': '09. Farini', 
            'Garibaldi': '14. Garibaldi', 
            'Kennedy': '21. Kennedy', 
            'Ospedale Maggiore': '02. Ospedale Maggiore', 
            'Ponte di Mezzo': '06. Ponte di Mezzo', 
            'Repubblica': '15. Repubblica', 
            'Rondani': '17. Rondani', 
            'Santa Croce': '07. Santa Croce', 
            'Stazione FF.SS.': '05. Stazione FF.SS.', 
            'Toschi': '16. Toschi', 
            'Traversetolo': '03. Traversetolo', 
            'Vittoria': '23. Vittoria'
        }